const CONSTANTS = {
  PROFILE_OPEN_CLOSE: "PROFILE_OPEN_CLOSE",
  NOTIFICATION_OPEN_CLOSE: "NOTIFICATION_OPEN_CLOSE",
  GET_STUDENT_DETAILS: "GET_STUDENT_DETAILS",
  GET_INSTITUTE_DETAILS: "GET_INSTITUTE_DETAILS",
  GET_ALL_INSTITUTES: "GET_ALL_INSTITUTES",
  GET_ALL_STUDENTS: "GET_ALL_STUDENTS"
};

export default CONSTANTS;
